### ISSUE TITLE
checkbox toggling on multiple (visually selected) lines

### ISSUE THREAD

**Issue by kraxli** [SidOfc/mkdx#115]
Hi
thanks for the this plugin. I am looking forward to replace vimwiki with.

A suggestion. Would it be possible to toggle multiple list items base on a selection (v or x mode)?

OS: **Linux Mint 20 Ulyana**
Vim: **NVIM v0.4.4**

**Example**:

Settings: `let g:mkdx#settings = { 'checkbox': { 'toggles': [' ', '-', 'x'] } }` 

1. Open a markdown file.
2. make a list:
```
- [ ] open task
- [-] task in progress
```
3. select multiple item 
4. toggle all items together (visual mode)

**Expected**:
all items are toggle once moving each of them to its own next item:
```
- [-] open task
- [x] task in progress
```

**Comment by SidOfc** [comment]
Hello @kraxli,

This should already be possible in visual mode ([documentation link](https://github.com/SidOfc/mkdx#completing-checkboxes--checklists)). Is it not working when you go into visual mode and then use the same mapping you use in normal mode? Note that when doing this in a deeply nested list parent items may not always move to the next state due to unfinished child list items.

**Comment by kraxli** [comment]
thanks @SidOfc

my bad. I had it mapped to normal only. Sorry for this. It works perfectly.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by SidOfc** [comment]
No problem, let me know if you find more issues :+1:
