### ISSUE TITLE
suggestoin for list item / check box toggling

### ISSUE THREAD

**Issue by kraxli** [SidOfc/mkdx#118]
@SidOfc, you provide a wide variety for toggling list and check-list items.

Would it be possible to have the following sequence for toggling list / check-list items in combination (one key map for next and one for previous):
```
text <-> - text <-> - [ ] text <-> - [-] text <-> - [x] text <-> text
```
So in words: `simple text`  <-> `list itme`  <-> `check-list item (to do)`  <->  `check-list item (in progress)`  <-> `check-list item (done)`  <-> `simple text`
?

My setting: 

```vim
    let g:mkdx#settings    = {  'checkbox': { 'toggles': [' ', '-', 'x'] }, }
```

**Comment by SidOfc** [comment]
I think adding this would not really add much value since this can already be achieved in the following way:

- <kbd>leader</kbd><kbd>lt</kbd>
- <kbd>leader</kbd><kbd>=</kbd> x2 or <kbd>leader</kbd><kbd>-</kbd> to go from `[ ]` to `[x]`

So instead of 1 mapping, there's two, the difference is both focus on doing one thing, which is for `ll` / `lt` to toggle an item to/from a list / task list item depending on its current state, and for `=` to toggle the next checkbox state.

I made them modular so they could be used to toggle list styles from one to another over having a single mapping which scrolls through them all. I'll try to explain what I mean.

Say I'm thinking about removing all list styles from a list item, I don't want to think about how many times to repeat (or prefix with a count) a mapping to get to the desired state, if it's a task list item I can just toggle it off using <kbd>leader</kbd><kbd>lt</kbd> and we're done.

I think this also doesn't work too well for creating pending / checked items, in my opinion it makes more sense to cycle through list styles starting from "no list item" to "unordered list item" to "ordered list item" and then going back to "no list item", excluding anything related to checking task list items. I feel that this mixes the creation of list items with updating a task list. 

The benefit would be the ability for users to cycle through all the different types of list styles, although I don't think that will be used very often since mkdx continues any list style you define, if you start with `- list item` and press enter, mkdx will prefix the next line with a `-`, same goes for `*`, `1.`, `- [ ]`, etc...

It ended up being quite a wall of text, sorry for that :sweat_smile:, if you've got strong opinions about mkdx supporting this please feel free to continue the discussion, if not I think I'll close this issue for now and who knows it may pick up steam if more users want this. 

Let me know and as usual, cheers for the request and feedback, always useful and appreciated :+1:

**Comment by kraxli** [comment]
sure @SidOfc, your view also makes sens! Thanks

**Comment by SidOfc** [comment]
No problem, as always cheers for the feedback and don't be afraid to propose other ideas as well, I'm always open to look at it :+1:
