### ISSUE TITLE
List Enter feature not working when using vim-pear

### ISSUE THREAD

**Issue by pwntester** [SidOfc/mkdx#120]
Hi,

Thanks for the great plugin! Im having an incompatibility problem though. It seems like the List Enter feature does not work when using [vim-pear](https://github.com/tmsvg/pear-tree) which is a popular tree for managing token pairing. Wondering if this is something that could be fixed or is an incompatibility between both plugins.

Thanks!

**OS type**:

- [x] Unix
- [ ] Windows
- [ ] Other ([SPECIFY])

**Vim**:

- [ ] vim
- [x] neovim
- [ ] Other ([SPECIFY])

**Vim version**:

For nvim: `v0.5.0-a6be7a918`

**Reproduce steps**:

Example:

1. Open a markdown file.
2. Create a list item
3. Hit enter

**Expected**:

A new item token is placed in the following line

**Actual**:

New line does not contain list token

**Comment by SidOfc** [comment]
Hiya @pwntester!

Cheers for the feedback, indeed this is a plugin conflict, a similar issue was posted before where the author ended up using [this snippet](https://github.com/SidOfc/mkdx/issues/102#issuecomment-629003420):

```
if exists('g:mkdx#settings')
    autocmd FileType markdown let b:pear_tree_map_special_keys = 0
endif
```

This prevents pear-tree from remapping enter _only_ in markdown files and thus this allows mkdx's enter handler to work.
Since this is also the first time I'm getting the same issue twice, I may add a FAQ section starting with this pear-tree fix :)

Cheers for the feedback and let me know if this doesn't work for you, in the meantime I'll close this issue :+1:

**Comment by pwntester** [comment]
Worked great, thanks!
