### ISSUE TITLE
`gf` bug

### ISSUE THREAD

**Issue by Delayless** [SidOfc/mkdx#122]
```
[Youtebe](https://youtube.com/)
[Google](https://google.com/)
```
I press gf on "google" and nvim will open Youtube. Unless I insert a blank line between the two links.

The same:
```
![picture](./Pictures/Screenshot.png)
[Youtube](https://youtube.com/)
[Google](https://google.com/)
```
I press gf or gx on anywhere(picture, youtube, google), then always open the picture.

**Comment by SidOfc** [comment]
Hello @Delayless, thanks for opening an issue!

I can indeed confirm this is a bug, it happens because I'm using the highlighting group to determine on which link you are, so multiple consecutive links are not distinguishable because they all have the same highlight group. I can't fix it right now but will look into it as soon as possible.

Until that time I don't think there is a "clean" fix, aside from disabling `g:mkdx#settings.gf_on_steriods` for now and sticking with the Vim default `gx` mapping if you use NetRW.

Cheers for reporting :+1:

**Comment by SidOfc** [comment]
Hi @Delayless,

I've fixed the issue by limiting gx/gf to the line the cursor is on, let me know if this issue still occurs on your side after you've updated mkdx.

Cheers for the find :+1:
