### ISSUE TITLE
Error raised after sourcing vimrc: "Key not present in Dictionary: highlight.enable"

### ISSUE THREAD

**Issue by victorkristof** [SidOfc/mkdx#125]
Hi @SidOfc,

I have this problem for quite some time now but finally decided to open an issue.

I remember I read somewhere someone had the same bug, but I can't find where... Sorry if it's a duplicate.

**OS type**:

- [x] Unix
- [ ] Windows
- [ ] Other ([SPECIFY])

**Vim**:

- [x] vim
- [ ] neovim
- [ ] Other ([SPECIFY])

**Vim version**: 8.2.539

**Reproduce steps**:

Basically, when I source my vimrc from within Vim in a Markdown buffer, I get the following error message:
```
Error detected while processing /Users/kristof/.vim/plugged/mkdx/after/syntax/markdown/mkdx.vim:
line    1:
E716: Key not present in Dictionary: highlight.enable != 1) | finish | endif
line  131:
E171: Missing :endif
```

And after that, I can't add new lines (with `<CR>` in insert mode or `o` in normal mode) without the following error message:
```
Error detected while processing function mkdx#OHandler:
line    1:
E716: Key not present in Dictionary: enter.o || !g:mkdx#settings.enter.enable)
```

**Expected**:

No error 😋 

**Actual**:

An error 😞 

Let me know if you need more details!

**Comment by SidOfc** [comment]
Hi @victorkristof!

I can confirm this happens indeed, it happens when `g:mkdx#ettings` is defined in your vimrc but it does not have a `highlight` key, until I've fixed it, you can add this to your config:

```viml
let g:mkdx#settings = {
    \ 'highlight': { 'enable': 0 }
\ }
```

This makes sure the setting exists and should not cause any errors, of course if you do want the highlighting set it to `1` instead of `0`. I'm going to look into it in the meantime :+1:

**Comment by SidOfc** [comment]
Alright, I checked it out and noticed that `after/syntax/markdown/mkdx.vim` loads before the plugin initialization code located in `ftplugin/markdown/mkdx.vim`. To fix it I created `plugin/mkdx.vim` which loads on vim startup and moved setting initialization to that file. This ensures settings are merged / guarded before opening any markdown file.

Cheers for the find :+1:

**Comment by victorkristof** [comment]
That was fast, well done!

**Comment by AckslD** [comment]
I have a similar error but for a different key:
```
E716: Key not present in Dictionary: "conceal == 1)"                
E15: Invalid expression: (g:mkdx#settings.links.conceal == 1)
```

**Comment by SidOfc** [comment]
Hello @AckslD,

hmmn can you provide me with some additional information such as which vim you are using and which version?
I'd also like to see any vim config you added related to setting up mkdx.

**Comment by AckslD** [comment]
Hi @SidOfc! Thanks for your response.

I'm currently on neovim v0.5.0-dev+1265-g66f9dd3c6.

I'm using packer as a package manager as follows:
```
    use {
        {'SidOfc/mkdx', config = 'require("plugin_settings.mkdx")', ft = {'markdown'}},
    }
```
together with the file `"./plugin_settings/mkdx.lua"`:
```
vim.g["mkdx#settings"] = {
    highlight = {enable = 1},
    enter = {shift = 1},
    links = {external = {enable = 1}, conceal = 1},
    toc = {text = 'Table of Contents', update_on_write = 1},
    fold = {enable = 1},
}
```
where I added the `conceal`-value to fix one of the errors.

**Comment by SidOfc** [comment]
Hmmn I see, I've never actually heard about this package manager before, mkdx does work with all major package managers though so I doubt this is an issue with mkdx itself but rather has to do with the way it's loaded.

mkdx expects the default plugin/mkdx.vim file to be loaded eagerly, I'm not sure if this package manager prevents that from happening. Can you try it without `ft = {'markdown'}`?

I've had errors like this before which is why I've moved config setup specifically to the plugin folder to ensure mkdx's settings were loaded before entering any markdown file.

**Comment by AckslD** [comment]
Hmm, interesting, removing `ft = {'markdown'}` indeed solved the issue!

**Comment by SidOfc** [comment]
Yeah I figured it must have been the way this package manager loads vim plugins, glad the issue is resolved for packer as well by removing the lazy loading aspect :+1:

**Comment by AckslD** [comment]
For anyone stumbling on this, a better fix than removing `ft = {'markdown'}` is actually to set the settings using `setup` rather than `config` :)
