### ISSUE TITLE
Using vim 8 built-in package manager - E121 Undefined variable: g:mkdx#settings, custom prefix not working, no helptags generated.

### ISSUE THREAD

**Issue by vicmortelmans** [SidOfc/mkdx#131]
Hi,
I'm using vim 8.0.1453 on ubuntu 18.04.
This is the **first time that I install a vim plugin**. Since I read that **vim 8 has it's own plugin manager built-in**, I decided to use that. I cloned mkdx in my `~/.vim/pack/foo/start` and I added` let g:mkdx#settings.map.prefix = ','` to my `~/.vimrc`.
This is what I get when starting vim:
```
Error detected while processing /home/vic/.vimrc:
line   53:
E121: Undefined variable: g:mkdx#settings
```
I have seen this other issue with a similar error ([https://github.com/SidOfc/mkdx/issues/102](https://github.com/SidOfc/mkdx/issues/102)), which in the end was a conflict between plugins, but since this is my first plugin, that shouldn't be the issue.
Here's the output of some of the investigating commands that were mentioned in the other issue:

`:verbose map`

```
   <C-H>         <C-W>h
        Last set from ~/.vimrc
   <NL>          <C-W>j
        Last set from ~/.vimrc
   <C-K>         <C-W>k
        Last set from ~/.vimrc
   <C-L>         <C-W>l
        Last set from ~/.vimrc
   @@x           !%xmllint --format --recover -
        Last set from ~/.vimrc
v  gx            <Plug>NetrwBrowseXVis
        Last set from /usr/share/vim/vim80/plugin/netrwPlugin.vim
n  gx            <Plug>NetrwBrowseX
        Last set from /usr/share/vim/vim80/plugin/netrwPlugin.vim
v  <Plug>NetrwBrowseXVis * :<C-U>call netrw#BrowseXVis()<CR>
        Last set from /usr/share/vim/vim80/plugin/netrwPlugin.vim
n  <Plug>NetrwBrowseX * :call netrw#BrowseX(expand((exists("g:netrw_gx")? g:netrw_gx : '<cfile>')),netrw#CheckIfRemote())<CR>
        Last set from /usr/share/vim/vim80/plugin/netrwPlugin.vim
```

`:verbose imap`

`No mapping found`

Typing the prefix ',' doesn't do anything (as expected: it gave an error), but the plugin is loaded, because `:call mkdx#ToggleList()` is working!

Most probably my problem isn't a mkdx bug either, but due to my lack of understanding how vim plugins should be configured. 

Using `:scriptnames`, I can see that the plugin is loaded, but after my `~/.vimrc`, so that probably explains the error. 

Is the built-in plugin manager doing things differently than Vundle, Pathogen or consorts? 

```
  1: /usr/share/vim/vimrc
  2: /usr/share/vim/vim80/debian.vim
  3: /usr/share/vim/vim80/syntax/syntax.vim
  4: /usr/share/vim/vim80/syntax/synload.vim
  5: /usr/share/vim/vim80/syntax/syncolor.vim
  6: /usr/share/vim/vim80/filetype.vim
  7: ~/.vimrc
  8: /usr/share/vim/vim80/syntax/nosyntax.vim
  9: ~/.vim/colors/solarized.vim
 10: /usr/share/vim/vim80/plugin/getscriptPlugin.vim
 11: /usr/share/vim/vim80/plugin/gzip.vim
 12: /usr/share/vim/vim80/plugin/logiPat.vim
 13: /usr/share/vim/vim80/plugin/manpager.vim
 14: /usr/share/vim/vim80/plugin/matchparen.vim
 15: /usr/share/vim/vim80/plugin/netrwPlugin.vim
 16: /usr/share/vim/vim80/plugin/rrhelper.vim
 17: /usr/share/vim/vim80/plugin/spellfile.vim
 18: /usr/share/vim/vim80/plugin/tarPlugin.vim
 19: /usr/share/vim/vim80/plugin/tohtml.vim
 20: /usr/share/vim/vim80/plugin/vimballPlugin.vim
 21: /usr/share/vim/vim80/plugin/zipPlugin.vim
 22: ~/.vim/pack/foo/start/mkdx/plugin/mkdx.vim
 23: ~/.vim/pack/foo/start/mkdx/autoload/mkdx.vim
 24: /usr/share/vim/vim80/syntax/markdown.vim
 25: /usr/share/vim/vim80/syntax/html.vim
 26: /usr/share/vim/vim80/syntax/javascript.vim
 27: /usr/share/vim/vim80/syntax/vb.vim
 28: /usr/share/vim/vim80/syntax/css.vim
 29: ~/.vim/pack/foo/start/mkdx/after/syntax/markdown.vim
```

Best regards,
Vic

**Comment by SidOfc** [comment]
Hi @vicmortelmans!

Nice to see you're trying out plugins, mkdx has quite a lot of documentation but it seems like you tried to use:

```viml
let g:mkdx#settings.map.prefix = ','
```

directly in the vimrc, in the [settings section of the documentation](https://github.com/SidOfc/mkdx#gmkdxsettings) it states that this is not possible (as a matter of fact, it is not possible due to exactly this error).

You should be able to specify the settings like this:

```viml
let g:mkdx#settings = {
\ 'map': { 'prefix': ',' }
\ }
```

If you'd like to find out how to add more settings you can see them all at `:h mkdx-settings` :)

Please let me know if this solves the issue for you, feel free to close if it does as well.

**Comment by vicmortelmans** [comment]
Hi,
I can now set the prefix in my `.vimrc` without errors being displayed, but there still seems to be something wrong with my setup. 
1/ help is not working: `:h mkdx-settings` gives `E149: Sorry, no help for mkdx-settings`
2/ the prefix doesn't seem to be working. When I press ',' in normal mode, the screen blinks, but it doesn't seem to be taking any further commands. Yet the prefix is mapped, because `:echo g:mkdx#settings.map.prefix` returns ','.
Still, the plugin seems to be there, because `call mkdx#ToggleList()` works...
Best regards,
Vic

**Comment by SidOfc** [comment]
Hi @vicmortelmans, hmmn I don't know too much about vim's native package manager as I'm using vim-plug myself. That being said though if you can share a link to your vimrc file I'd be happy to check out if I can get it to work using your configuration, and make any necessary changes to make mkdx compatible with Vim's built-in package manager otherwise.

Reason I'm thinking mkdx is not compatible is due to the directory structure looking different in `:h packages` which includes some references to a `start` folder which mkdx does not have. Perhaps I'll have to add some install instructions or add a directory to mkdx for pack to pick it up.

Glad to hear the initial issue was indeed fixed, please share a link to your vimrc (or play around with the info in `:h packages` yourself) so I can check it out. Cheers for the feedback so far!

**Comment by vicmortelmans** [comment]
Hi, 
here's my .vimrc:

```
set background=light
set display+=lastline
set enc=utf-8
set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar
set hlsearch
set linebreak
set mouse-=a
set ruler
set softtabstop=2 shiftwidth=2 expandtab
set showcmd
set visualbell
"nmap <up> gk
"nmap <down> gj
map @@x !%xmllint --format --recover -
syntax on
syntax enable
let g:solarized_termcolors=256
let g:solarized_termtrans=1
colorscheme solarized
if has('win32')
  set backupdir=$HOME/.vim/backup,.
  set directory=$HOME/.vim/temp//,.
  set undodir=$HOME/.vim/undo,.
else
  set backupdir=~/.vim/backup,.
  set directory=~/.vim/temp//,.
  set undodir=~/.vim/undo,.
endif
if has('gui_running')
  set lines=60 columns=100
  if has("gui_gtk2") || has("gui_gtk3")
    set guifont=Go\ Mono\ 12
  elseif has("gui_photon")
    set guifont=Go\ Mono:s12
  elseif has("gui_kde")
    set guifont=Go\ Mono/12/-1/5/50/0/0/0/1/0
  elseif has("x11")
    set guifont=-*-courier-medium-r-normal-*-*-180-*-*-m-*-*
  else
    set guifont=Go_Mono:h12:cDEFAULT
  endif
endif
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
let g:mkdx#settings = {
\ 'map': { 'prefix': ',' }
\ }
```
In `:h packages` I didn't find anything related to the help files, but [here](https://stackoverflow.com/a/57738713/591336) I found out that running `:helptags ALL` once, fixes the issue with the helptags. It looks like I only have to this once, it's not needed in my `.vimrc`. 

Remains only the issue with the custom prefix not working...

Thans for following up!
Vic

**Comment by SidOfc** [comment]
Good stuff @vicmortelmans, glad you were able to solve the helptags issue as well, will probably add a section to the README about installing with vim's built-in package manager after I've looked into and fixed the issue you're experiencing.

Cheers for sharing your vimrc, will give it a quick look ASAP, but going to bed now! :D

**Comment by SidOfc** [comment]
Hmmn alright, I've looked into it a bit, managed to get mkdx "installed" but I see that `mkdx/ftplugin/markdown/mkdx.vim` (which defines the mappings) just doesn't get loaded at all. The only thing I can find about it are runtime path hacks which I can't use because this file should be loaded only in markdown files and not at startup.

I went a bit further and pushed a commit which moves `mkdx/ftplugin/markdown/mkdx.vim` to `mkdx/ftplugin/markdown.vim` (a more common location) but it changes nothing in Vim unfortunately.

There is one solution for Vim that I came up with which is to manually source the file in question whenever a markdown file is opened, e.g. if you clone a **new copy** of mkdx into `~/.vim/pack/foo/start/`:

```shell
cd ~/.vim/pack/foo/start
git clone https://github.com/SidOfc/mkdx.git
```

and add this at the bottom of your vimrc:

```viml
if !has('nvim')
  augroup MKDX
    au!
    au FileType markdown so $HOME/.vim/pack/foo/start/mkdx/ftplugin/markdown.vim
  augroup END
endif
```

It will work as intended in regular Vim. I also tested this in neovim 0.5, and there it actually worked properly out of the box after cloning mkdx into `~/.local/share/nvim/site/pack/foo/start/`, without adding any extra vimscript.

I guess the simplest fix you could apply would be to copy the autocommand snippet and paste it at the bottom of your vimrc, but seeing as Vim's own system doesn't seem to always load ftplugin files I'd recommend using either an external plugin manager such as [vim-plug](https://github.com/junegunn/vim-plug) or to use neovim instead as that seems to load everything just fine.

Let me know if it's not working, any part is confusing, or if you've found a way to fix this properly as I'd still be interested in making Vim work "natively" just like neovim does!

**Comment by vicmortelmans** [comment]
Hi, 
I've decided to adopt vim-plug and that did the job! (just tested this on vim in cygwin)
Thanks for the support!
Vic

**Comment by SidOfc** [comment]
Sounds good :+1: 

I'll keep a lookout for more installation issues using regular Vim's native package manager, maybe in the future it can be fixed or will be patched by Vim itself.

Thanks for the feedback and enjoy :+1:
