### ISSUE TITLE
mkdx#WrapText wraps incorrectly after a special / accented character is used in a line.

### ISSUE THREAD

**Issue by kiil** [SidOfc/mkdx#135]
**OS type**:

- [ ] Unix
- [ ] Windows
- [x ] Other ([MacOs])

**Vim**:

- [x ] vim
- [ ] neovim
- [ ] Other ([SPECIFY])

**Vim version**:

For vim: `vim -v`
version 8.2.2050

**Reproduce steps**:

Example:

1. Open a markdown file.
2. Paste the following example into the file:

There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.

3. Then, attempt to do leader+b in NORMAL mode on the 'a' before 'passage' with :set lbr.

**Expected**:

only 'a' should be surrounded by \**

**Actual**:

More or other letters / words are sourrounded by \**.

See:

![mkdx](https://user-images.githubusercontent.com/1455044/100986089-0b1aed00-354d-11eb-952f-3491afcee2b8.gif)

This also happens with ln command, / command and others.

**Comment by kiil** [comment]
Now tested in neovim with clean init.vim - except for this plugin - and same problem.

Also tested in vim with clean .vimrc. This seems to be a real bug when linebreak is turned on.

**Comment by kiil** [comment]
Not only does the commands often seems to target wrong words when using them on short words towards the end of longer "broken" lines - when linebreak is set the cursor will also jump around quite unpredictably when using the toggle commands on words in longer lines towards the end.

**Comment by SidOfc** [comment]
Hello!

Hmmn, never actually tested `:set linebreak` so that's a new one for me, will have to figure out what exactly it does or perhaps disable `linebreak` before executing an action and then set it back to its original value after execution :thinking: 

Thanks for supplying a screenshot and additional comments, I will look into it (hopefully tomorrow) :+1:

**Comment by kiil** [comment]
> perhaps disable linebreak before executing an action and then set it back to its original value after execution

That's actually quite clever :)

**Comment by SidOfc** [comment]
Hi again @kiil,

If I `:set lbr` and `:set wrap` it seems the correct word/character under the cursor is still marked, I do however notice the cursor jumping one character "forward" when unwrapping but it doesn't describe the issue you're showing in the gif.

You said that you had a clean vimrc file, would you mind dumping the contents in a code snippet here or share a link to a gist so I can try it out?

**Comment by kiil** [comment]
For example with this vimrc:

`set lbr

let mapleader = "<"

call plug#begin('~/.vim/plugged')
Plug 'SidOfc/mkdx'
call plug#end()`

 Moving the cursor over 'i' in

> Man kan ikke blæse og have mel i munden.

and pressing <Leader> + b

Will result in 


> Man kan ikke blæse og have \**mel\** i munden.

Instead of

> Man kan ikke blæse og have mel \**i\** munden.

So in fact it seems the line does not even need to be very long for the problem to appear on short words.

**Comment by kiil** [comment]
PS. I've tried with other mapleaders as well. Same result.

**Comment by SidOfc** [comment]
I see, actually this has nothing to do with the `linebreak` setting. It breaks in the same way when it is disabled. I already thought it was a bit weird since the description of `linebreak` also states it is "visual" but I just assumed the issue was related to that, I should have asked for a test w/o linebreak on to exclude it right away :sweat_smile:

Another notable observation is that it doesn't happen before the word `blæse` but after it does, I've tested it a bit further using `æ` / `í` and indeed if special / accented characters appear it seems to fail whenever the cursor is placed past that character.

It is now clear what I'm looking for even though I'm still a bit stumped. I will check it out tonight and hopefully find a fix. Thanks for the minimal vimrc and providing a second example using different text, that helped a lot in narrowing down potential causes :+1:

**Comment by SidOfc** [comment]
@kiil I've pushed a commit to master which seems to fix the issue for strings containing accented / special characters.

Can you confirm?

**Comment by kiil** [comment]
Strange. I also had problems with som Ipsum Lorem text that did not contain any "foreign" characters.

Yes! I'll be happy to test "master" - I'll try to find out how to get master with the plug manager :)

**Comment by kiil** [comment]
Yes. It fixes it!

Thanks a lot! And sorry for misleading you with the linebreak stuff. Don't know why that seemed to make a difference under certain circumstances.

**Comment by kiil** [comment]
(There is now a very minor issue where it will do `\*i.\*` on a line ending in 'i.' - but correctly do `\*nu\*.` for a line ending in 'nu.')

**Comment by SidOfc** [comment]
Hey @kiil, no problem, it was not intentionally misleading (I've put folks on the wrong trail before, no worries) :)

Vim Plug uses `master` by default so you can always just `:PlugUpdate` from within vim to pull latest changes too.

I'll look into the issue with wrapping at the end with single char words as well, might not be today but will be sooner rather than later.

Thanks for the feedback so far, it was quite constructive and useful!

**Comment by SidOfc** [comment]
Alright, single character wrapping should now also work with most punctuation, as a matter of fact if you had `i.` in the middle of a line it would also fail because the checks only checked for spaces before and after the character under the cursor. Now it checks for spaces, tabs, newlines, and some common punctuation: `.` / `,` / `'` / `"` / `;` / `:` / `!` / `?`

**Comment by kiil** [comment]
I can confirm this works also now. Thanks a lot.

So far no other problems.

:)

**Comment by SidOfc** [comment]
Awesome, do keep me posted though! I've probably missed some other edge cases as well.

:+1:
