### ISSUE TITLE
Question, combining jumps and goto file

### ISSUE THREAD

**Issue by m-fonseca** [SidOfc/mkdx#139]
Hello, 

Just came across this plugin and wanted to start customizing a little bit.  I want to map the standard ctrl-] (jump to definition) for doing jumps to other files and anchors in a document (trying not to learn even more key bindings).

Currently using
```
autocmd FileType markdown nnoremap <C-]> :call mkdx#JumpToHeader()<CR> 
```

Is there an easy way to combine jumps and goto file logic in a single call so it will either jump to a local anchor or jump to a file depending on the underlying link type (and then It just works, and I don't have to think about it)?

Thank you!

**Comment by SidOfc** [comment]
Hello!

I think this can be achieved by checking what's under the cursor but depending on viml experience it can get quite ugly to code.
What you could start with is instead of `: callmkdx#JumpToHeader()`, create and call a wrapper function like `:call myJumpWrapper()`.

This function will then have to identify whether it is on a link and if so, whether it links to a header (starts with `#`) or is a file (can be checked using `:h filereadable`). The implementation for `mkdx#JumpToHeader` is quite complex since I think I wrote it to also work if the cursor is not on a link (which then picks the nearest linkj), but it does have some link detection logic which might be usable: https://github.com/SidOfc/mkdx/blob/master/autoload/mkdx.vim#L1347

**Comment by totpet** [comment]
Hi!

I think an easier solution would be to simply try jumping to the header and checking if it happened, instead of trying to find out manually. Something like this:

```vim
function! jumpHeaderOrFile()
    let pos1 = getpos('.')
    call mkdx#JumpToHeader()
    let pos2 = getpos('.')
    if pos1 == pos2
        norm gf  " or whatever else you want to use for jumping to file
    endif
endfunction

**Comment by m-fonseca** [comment]
Excellent.  Thank you guys!
