### ISSUE TITLE
Question: How to generate a TOC one level below the current heading?

### ISSUE THREAD

**Issue by m-fonseca** [SidOfc/mkdx#142]
When generating a TOC, it always generates at the same level of the current heading.  How do I generate it one level below the heading its under?

I.e. if my cursor is below a \# heading, I would like a \#\# to be generated.  Theres a lot of settings for the TOC but I didn't see one that addressed this?

Thank you!

**Comment by SidOfc** [comment]
@m-fonseca The TOC is always seen as a top-level heading because it covers the entire document. Therefore if you'd nest the TOC and create another top-level heading below it, it wouldn't make sense for the TOC to be nested in a "subsection"

That said though if your document structure only uses H1 for the title, and H2 or lower for the rest, it could make sense to have a `default_toc_level` setting perhaps. The rest of the TOC would still be generated all the same but the TOC itself could then have extra `#` appended.

Is that something that would be of interest?

**Comment by m-fonseca** [comment]
@SidOfc Yes, my documents usually have one H1, (the title).  If I have more then one, the markdown linter yells at me.  (I guess you can also have the title in the *front matter*, but I don't usually use those).

I think the `default_to_level` could be useful (certainly to me it would be!).

**Comment by SidOfc** [comment]
I'll see what I can do here, it might be more difficult than I'm expecting since the code for generating TOCs is quite complex already and I didn't write it in a good way at all. Unfortunately this has become major undertaking to change to something easier to maintain, but I'll check it out nonetheless :+1:

**Comment by m-fonseca** [comment]
Sounds good to me :+1:

**Comment by SidOfc** [comment]
Hello @m-fonseca, I realise I left this issue in the dust. Apologies for that. To be honest with you I don't think it's worth the effort from my part to add this considering the amount of risk I'd be taking of breaking multiple other connected functionalities in addition to some other issues...

This plugin was the first "serious" vim plugin I decided to build, it became a bit of a monstrosity as a result and the TOC functionality is especially unstable because I wanted to add support for the details HTML structure so I could have folded TOC sections on GH as well 😅.

In the end, I can't see the forest for the trees anymore when I look at the TOC code. Additionally, I'm pretty much too lazy and disconnected from the TOC code to dive deep into it anymore.

All that being said, happy new year nonetheless and let's make the best of 2022. Cheers for taking the time for this feature request and your patience 👍

**Comment by m-fonseca** [comment]
No problem.  Thanks for the plugin!
