### ISSUE TITLE
mkdx-enter and nvim-compe <CR>

### ISSUE THREAD

**Issue by zetashift** [SidOfc/mkdx#145]
Hiya! I'm using [compe](https://github.com/hrsh7th/nvim-compe) and [lexima](https://github.com/cohama/lexima.vim) and I can't get snippets to work when I press `<CR>` to insert a snippet on the autocomplete menu. It simply inserts a newline.
This might have to do with mkdx-enter from what I see? I don't think this is a bug or anything, but I'm new to (neo)vim and like to know how I could solve this.

![image](https://user-images.githubusercontent.com/1857826/114579000-bc5d2c80-9c7d-11eb-89db-bde615adf36d.png)

**OS type**:

- [X] Unix
- [ ] Windows
- [ ] Other ([SPECIFY])

**Vim**:

- [ ] vim
- [X] neovim
- [ ] Other ([SPECIFY])

**Vim version**:

For nvim: `nvim -v`
```
NVIM v0.5.0-dev+1236-g1b030f889                                                                                                                                
Build type: RelWithDebInfo   
```
**Reproduce steps**:

1. Install compe and map `<CR>` to  `compe#confirm`
2. Try to use a snippet: 
![image](https://user-images.githubusercontent.com/1857826/114579178-e57dbd00-9c7d-11eb-80ff-3b9042c2de32.png)

**Expected**:

Snippet is inserted

**Actual**:
Instead a newline is created.
![image](https://user-images.githubusercontent.com/1857826/114579225-f2021580-9c7d-11eb-8a4d-ce4198d622a3.png)

**Comment by SidOfc** [comment]
Hello @zetashift and welcome to (neo)vim! Yes, this stuff can be tricky sometimes since mkdx does indeed overwrite enter, if it didn't do this things such as list continuation would not work. If you prefer the snippet plugins over mkdx's functionality you can [disable the enter handler](https://github.com/SidOfc/mkdx#gmkdxsettingsenterenable).

 Alternatively I see you're using this snippet to quickly insert a fenced code block, mkdx also has functionality so that when you type 3 consecutive backticks or tildes it will create:
 
 ``````markdown
 ```|
 ```
 ``````
The cursor will be placed where I put the vertical bar `|` so you can type the language straight afterwards and press enter to type your code.

I'm not sure if this is something I can fix since other plugins that use Enter also don't combine well with mkdx but the least I can do is try.

**Comment by zetashift** [comment]
Ah, thanks!! I use the snippets for easily typing a code fence + language indeed, I might remap it to something different cause I feel like I'm running into this issue more often haha. Or just use mkdx and a lil' bit more typing.

As a followup, is there away to get (smart/auto) indentation in code blocks? E.g.:

```
def foo() {|}
```
Pressing enter on the vertical bar `|` will result in:

```
def foo() {
  |    <-- indented here.
}
```

**Comment by SidOfc** [comment]
Unfortunately this isn't trivial since every language has different spacing and style rules, I'd say for larger snippets it'd be easier to open a new buffer using `:spl` to create a horizontal split, then `:enew` to empty the buffer, then `:set ft=ruby` or any other language and type your snippet there, then copy it over when you're done. If you need to do this often you can keep the buffer open but empty it with a command like `ggdG` and optionally `:set ft=python` or some other language.

Even if it was possible it's related to the initial issue in that it requires some kind of control over enter which I doubt mkdx can offer. If you find a plugin that does this and prefer that convenience over automatic list / quote continuation you're better off disabling mkdx's enter behavior.

There is a way to get the syntax highlighting in there by setting some option from [vim-markdown](https://github.com/tpope/vim-markdown) though, but when I used it I've found loading and scrolling through larger markdown files to become sluggish.

**Comment by zetashift** [comment]
Alright thank you very much for your help, it's hard to have an universal solution to this, for now I have enough to just get working.

**Comment by SidOfc** [comment]
You are indeed correct about it being hard to find a universal solution, unfortunately there is no way for any mapping to only "overwrite" within some specific context such as a list with mkdx's enter, that would be a great way to potentially solving all of the above!

Anyways I haven't checked out the original issue yet even though I don't have much hope there either, I'll reopen until I've checked it out and can give you a definite answer :)

**Comment by zetashift** [comment]
> unfortunately there is no way for any mapping to only "overwrite" within some specific context such as a list with mkdx's enter, that would be a great way to potentially solving all of the above!

I know almost no VimL, but maybe using something like https://github.com/ikatyang/tree-sitter-markdown one could get the context of what's currently being edited and based on that apply what to do with enter? Treesitter usage is more ergonomic for neovim though and I feel like it's out of scope for this plugin.

>Anyways I haven't checked out the original issue yet even though I don't have much hope there either, I'll reopen until I've checked it out and can give you a definite answer :)

Ah that's okay, either way ~bedankt~ thanks for your help!

**Comment by SidOfc** [comment]
The problem lies not within getting the proper context, but only consuming enter while in a specific context in which mkdx could be useful, it is this part that is not doable in VimL which prevents me from allowing more plugins to cooperate / keep working with mkdx.

Another problem with trying to implement tree-sitter is that this plugin should also work with regular vim, therefore I'd have to find a way to make it compatible which would be a nightmare just like jobs in VimL already are due to implementation differences between regular vim and neovim.

P.S. I'm also Dutch, what a coincidence :)

**Comment by zetashift** [comment]
> The problem lies not within getting the proper context, but only consuming enter while in a specific context in which mkdx could be useful, it is this part that is not doable in VimL which prevents me from allowing more plugins to cooperate / keep working with mkdx.

Ah I see, I find VimL hard to grok as is. But I'd also say the current behavior is "good enough".

> Another problem with trying to implement tree-sitter is that this plugin should also work with regular vim, therefore I'd have to find a way to make it compatible which would be a nightmare just like jobs in VimL already are due to implementation differences between regular vim and neovim.

Yeah totally understandable.

> P.S. I'm also Dutch, what a coincidence :)

Small world!

**Comment by cands** [comment]
I have a similar conflict with mkdx-enter and completions using coc.nvim, so I needed to disable mkdx-enter, but the functionality of mkdx-enter would be very handy for lists. I wonder would it be possible to have the 'o' (enter.o) and 'O' (enter.shifto) normal mode functions active while mkdx-enter is disabled? Disabling mkdx-enter seems to disable also enter.o and enter.shifto, it would still be handy to have the normal mode functions working even when mkdx-enter needs to be disabled due to conflicts that cannot be resolved (yet).

**Comment by SidOfc** [comment]
@cands I just pushed a commit which should allow this, are you able to verify?

As for the original issue, unfortunately I haven't been able to make any progress with it yet. There are some options that involve storing the old mapping and executing that when mkdx's enter otherwise wouldn't do anything but I haven't gotten anything to work properly and even if it did I believe more bugs than I could handle would arise from implementing this behavior.

For this reason I will close this issue, @cands even though it's closed feel free to reply with your confirmation :+1:

**Comment by cands** [comment]
Yes, I verify that it works now, thanks very much @SidOfc for the quick fix! The normal mode functions will be handy.

**Comment by zetashift** [comment]
> There are some options that involve storing the old mapping and executing that when mkdx's enter otherwise wouldn't do anything but I haven't gotten anything to work properly and even if it did I believe it would cause more bugs than I could handle by implementing this behavior.

Yup, I agree, I think current behaviour is good enough! Thanks for the great plugin :D
