### ISSUE TITLE
Documentation - Keybindings Table

### ISSUE THREAD

**Issue by theduke** [SidOfc/mkdx#153]
The functionality and documentation of this plugin is truly outstanding!
Great job.

The README could really use a short overview of the available keybindings, though.

Something like:

| Key | Action| 
| --- | --- | 
| Deadlink detection | `<Prefix>L` |
| ... | ... |

**Comment by SidOfc** [comment]
Hello @theduke, I believe this is what you are looking for: https://github.com/SidOfc/mkdx#mappings, it's been there all along :)

**Comment by theduke** [comment]
Yes indeed, exactly what I wanted.

I do suggest moving the mapping table before the settings section though, to make it a bit more discoverable.

**Comment by SidOfc** [comment]
Glad the issue is solved, I appreciate the suggestion to move the mapping table but I think I will keep it where it is right now for multiple reasons:

- Existing users already know the current position
- The word "mapping" is a common term in the Vim community, a lot of people will ctrl+f it if they don't see it
- The Table of Contents is placed very high on the page, if people ctrl+f "table" they will land there instantly

This does not mean however, that it will never happen. When more people come along with support for similar opinions I will definitely reconsider.
