### ISSUE TITLE
[Feature request] Simple one color highlight for ``` code blocks

### ISSUE THREAD

**Issue by mareksamec** [SidOfc/mkdx#155]
Would it be possible to add simple one color highlight for code blocks (regardless of the code language)? In default vim markdown highlight it is hard to distinguish normal text from code blocks. Added screens below.

This is plain vim with mkdx:
![image](https://user-images.githubusercontent.com/4179518/140037055-2949ed81-3cc1-4517-a8cf-a60de5bb2bba.png)

This is similar section displayed with **gabrielelana/vim-markdown** plugin. Unfortunately this plugin is a bit slow with nvim and has some overlaps with mkxd (where mkdx does far better job):
![image](https://user-images.githubusercontent.com/4179518/140036790-828800cc-f327-4c17-8d73-0f767fccd305.png)

**Comment by SidOfc** [comment]
Hello @mareksamec!

I see the issue here with distinguishing fenced code blocks, but I think their styling depends on the colorscheme you are using, for me they look like this already:

![image](https://user-images.githubusercontent.com/3225058/140067840-926c496a-1574-4e11-acc0-bcf838a95907.png)

That said, the syntax group for the _content_ of the fenced block (excluding delimiters) is `markdownCode`, you can style this yourself quite easily with:

```viml
highlight markdownCode ctermfg=12 guifg=Red
```

Which looks like this for me (guifg is shown here):

![image](https://user-images.githubusercontent.com/3225058/140068477-62cd7149-c632-44e4-9c18-44beae52765d.png)

Since mkdx already has some 40+ settings to allow circumventing some plugin conflicts and just for general customization, and because this is pretty much a one liner already, I don't think it really adds anything to implement within mkdx itself.

For this reason, I will close this issue, if you have any remaining questions about this however, feel free to comment in this issue.

**Comment by SidOfc** [comment]
I also forgot to mention that some users use additional plugins/settings to get syntax-specific highlighting for their code blocks, mkdx only does this for YAML/JSON frontmatter as to not become too sluggish while detecting / syncing the syntax groups (mixing lots of syntaxes in one file really slows down (n)vim).
