### ISSUE TITLE
mkdxLink highlight group improvments

### ISSUE THREAD

**Issue by lyndhurst** [SidOfc/mkdx#166]
Hi,

I was wondering if it could be possible to include two edge cases in the mkdxLink highlight group.

1. In the case of url links with an "anchor" included, the highlight group stops at the `#` anchor symbol
    Example: `https://www.blog.com/post#section`  
2. Sometimes it is just easier to omit the `https://` altogether
    Example: `www.google.com`

I hope it is not too much trouble, thank you for your time.

**Comment by SidOfc** [comment]
Hi @lyndhurst, I might be able to add URL fragment support and expand `mkdxLink` a bit to support more links that GitHub also recognizes when typing markdown. It won't allow you to simply "omit" `https://` though. It would still need to be prefixed with at least `www.` then for example (this is what GitHub supports).

Users will also not really be able to type `mail.google.com` and have it show up as a link since that would introduce way to many false-positives in the scanning process :)

**Comment by lyndhurst** [comment]
Nice, thank you. The fragment link case was the main reason I opened the issue, the second case was just a thought. :+1:

**Comment by SidOfc** [comment]
Should be good now, actually managed to make it quite a bit more flexible so it can also handle common-ish prefixes such as `ww1.somewhere.com`:

<img width="880" alt="image" src="https://user-images.githubusercontent.com/3225058/162476791-a1034b44-37f5-4587-bad7-7fc003320b8b.png">

For reference, this is how each of these links is parsed by GH:
- https://https-url.com
- http://http-url.com
- //inherit-protocol.com
- www.www-subdomain.com
- wwx.arbitrary-ww?-domain.com
- ww9.arbitrary-ww?-domain.com
- ww9.arbitrary-ww?-domain.com
- https://with-fragment.com#fragment-identifier
- https://with-query-and-fragment.com?a=1&b[]=4&c=1@!49280FSNJ908#fragment-identifier

**Comment by lyndhurst** [comment]
Thank you for being so reactive (as always!), I will only be able to check it tomorrow or later tonight though.
The extra parsing reference are a nice piece of info too, cheers :+1:

**Comment by SidOfc** [comment]
I do my best, thank you for the appreciation! And by all means, if the issue is not fixed, please do reopen or request for me to reopen if you can't 👍
