### ISSUE TITLE
Set shiftwidth/tabstop number of indent spaces

### ISSUE THREAD

**Issue by chrstnwhlrt** [SidOfc/mkdx#174]
Is there any way to set the number of indent spaces? I use shiftwidth=4 nowadays and prettier to format markdown, which also allows setting shiftwidth / tab-width / indent (number of spaces inserted in list eg.).

Is there any way to configure the number of indents for this incredible plugin?

**Comment by SidOfc** [comment]
Hello @chrstnwhlrt, hmn, it's been a fair amount of years ago since I actively implemented various parts of the plugin which would be affected by shiftwidth, I do believe that this "should just work" as in if you set it to 2 mkdx will parse lists etc using that indent size.

Did you find issues when using mkdx with shiftwidth set to 4? If so, can you list them so I can take a look at potentially relevant parts?

**Comment by chrstnwhlrt** [comment]
@SidOfc Thanks for the quick response. No not really an issue as I'm going to prettify the markdown anyway before saving, but just an inconvenience that mkdx and prettier don't follow the same set of rules for formatting. 
No need to trouble yourself, I thought I just might miss some configuration possibility there.

Thank you for the great work!

**Comment by SidOfc** [comment]
I see, thank you for the quick reply! Should this get traction from other folks who want the same I might consider implementing it. Cheers 👍
