### ISSUE TITLE
Conceal in syntax/after/markdown.md

### ISSUE THREAD

**Issue by Ginner** [SidOfc/mkdx#175]
Hi Sidney. Once again, thank you for your plug-in, I'm getting a lot of usage out of it :)

**OS type**:

- [x] Unix
- [ ] Windows
- [ ] Other ([SPECIFY])

**Vim**:

- [ ] vim
- [x] neovim
- [ ] Other ([SPECIFY])

**Vim version**:
NVIM v0.7.0

**Reproduce steps**:
In `~/.config/nvim/after/syntax/markdown.vim` I have the following:
```
syntax match customConceals '\[ \]' conceal cchar=4
syntax match customConceals "\[x\]" conceal cchar=5
syntax match customConceals "\\_" conceal cchar=_

highlight default link customConceals Normal
```

**Expected**:
Putting syntax changes in `after/syntax/<ft>.vim` modifies the syntax after the syntax from other config files are loaded and:
`- [ ]` should turn into `- 4` and `- [x]` into `- 5`.
`\\_` works as expected, and turns into `_`.

**Actual**:
`- [ ]` and `- [x]` are unaffected.

I can get it 'working' by doing: 
```
call matchadd('Conceal', '\[\ \]', 0, -1, {'conceal': '4'})
call matchadd('Conceal', '\[x\]', 0, -1, {'conceal': '5'})
```
But only by using the `Conceal` group, it doesn't work if I replace `Conceal` with `customConceals` for example, which will prevent me from doing further customization.

**Comment by SidOfc** [comment]
Hi @Ginner!

So you're trying to conceal or rather replace the checkbox marks with numbers if I understand correctly?

I also believe highlight groups should always start with a capital letter which your `customConceals` group does not. maybe this is why it fails with `matchadd`?

Not entirely sure yet if this is an mkdx issue or not atm, to verify this, can you disable mkdx and try again?

If the exact same code works works when mkdx is disabled I may need to check something in the syntax file.

**Comment by Ginner** [comment]
I should've clarified:

- I did confirm it was mkdx, by turning my plugins off one by one, and it does work as intended with just mkdx turned off.
- I've put the numbers in the description above as placeholders. In reality I wont to replace with some nerdfont check mark characters, which GitHub are not rendering correctly. Like [here](https://i.redd.it/9iu0i95rxt451.png)
- I tried to capitalize the first letter of the group with no effect.

**Comment by SidOfc** [comment]
Alright that's plenty of confirmation for me, cheers for the extra details 👍 
Marking this as a bug, will look into it when I have some spare time.

Thanks for the report!

**Comment by SidOfc** [comment]
@Ginner I've just pushed a commit which adds a new setting which allows customizing the `syn match` statements mkdx uses for `mkdxCheckboxEmpty`, `mkdxCheckboxPending`, and `mkdxCheckboxComplete` highlight groups.

This means you can now do something like:

```viml
let g:mkdx#settings = {
  'checkbox': {
    'match_attrs': {
      'mkdxCheckboxEmpty': 'conceal cchar=1',
      'mkdxCheckboxPending': 'conceal cchar=2',
      'mkdxCheckboxComplete': 'conceal cchar=3',
    }
  }
}
```

There is not much more that I can do though, and I'll also proactively mention here for anyone else reading this in the future that I do not intend to make every supported part of mkdx concealable in this way as it adds tons of clutter to already pretty cluttered code. 

The reason the patch is like this is because mkdx "also" loads its markdown file via its own `after/syntax/markdown.vim`. Additionally mkdx is a filetype plugin which means most of it only loads when editing a markdown file. Because of this, the plugin's "after" files load later than the ones you have locally.

It's probably a suboptimal implementation from my part which is "intensive" to change years down the road since that might unearth potentially many new issues when users update.

Anyways, there are ways to circumvent this, primarily by making sure your code loads "later" than mkdx, I haven't looked into ways of doing this but google is your friend :)

Anyways all that said I'll wait to see if this satisfies your needs, happy to see mkdx is still useful to you today :)

**Comment by SidOfc** [comment]
Cheers for the detailed explanation and research @Ginner, always appreciated :)

Yeah I did briefly try to get the syntax highlighting to also show up though quickly gave up on it as it wasn't the primary problem. That said I think it "should" be possible though I don't use conceal myself so not too familiar with that area 😅 

At any rate, at least now it is possible to make the checkboxes concealable which is where mkdx did get in the way. It's a good enough improvement for you to not have to be sorry too :)

Cheers for the support and understanding you usually bring, happy vimming 👍
