### ISSUE TITLE
Strikethrough/delete conceal issues

### ISSUE THREAD

**Issue by samarulmeu** [SidOfc/mkdx#176]
Hello, again!

By chance I discovered this issue. If you use `~~` in a heading line there will be no preview of the *deleted* word(s). In a normal paragraphs you get the line over the words. 

Also will be nice to have the `~~` concealed as in the case of italic or bold. 

A picture instead a thousand words 

![strike](https://user-images.githubusercontent.com/39216570/183877202-2a21736a-e2e2-42fc-a8de-3639b6b2129d.png)

Thank you for your help!

**Vim version**: 8.2.2434

**Comment by SidOfc** [comment]
Hey @samarulmeu, hope you're doing well :)

I see, these issues are clear indeed. I see two separate things here:

1. Issue: headers do not show strikethrough styling
2. Improvement: conceal strike markers for strikethrough text

Both seem relatively small but as with any of my highlighting adventures, I'm never really sure where to look 😅 I'll take a look soonish though it won't be today :)

Cheers for the report!

**Comment by samarulmeu** [comment]
Hello @SidOfc! I'm fine and hope you are also. 

No hurry, I know you are doing your best. And also it is holiday season... :wink:

**Comment by SidOfc** [comment]
Hello @samarulmeu,

I think I've patched the issue where the strikethrough highlighting is also applied within h1-6.

I've fiddled around with conceal a little bit but gave up pretty easily here. Primarily because I'll end up spending a bunch of my own spare time figuring out an issue for 1 "known" user who wants this.

I decoupled markdown strikethrough highlighting from html strikethrough so you can fiddle around with it yourself by playing around with `markdownStrike` if you want.

Finally if you think it will be a good addition to mkdx feel free to send in a pull request ;)

Just as a heads up: going forward I will no longer be accepting anymore niche syntax highlighting issues unless they are accompanied by a PR :)

If there are any issues with this patch, please do add feedback in the comments though, thanks for the report as usual!

**Comment by samarulmeu** [comment]
Hello @SidOfc ! Thank you for your work. I understand you completely about your time and I wished I could already send a PR, but I do not have the skills yet. It will be nice to have a _team_ that could care of the plugin. I still think that it is the best markdown plugin that offers almost everything you need. I only use your plugin. I will try to dig it deeper in the highlighting stuff.

My problem I thought to be more as an issue and not a _personal_ request as I thought that in the case of strikethrough it should have the same behavior as in italic or bold case.

Thank you again!

**Comment by SidOfc** [comment]
Yeah, I don't look at this from a personal request kind of perspective either. I don't have any info as to who uses what, only going relying on my own intuition and knowing a person uses it for sure by existence of an issue on github :) My own intuitin is admittedly naive in certain cases 😅 This leads me to want to please whoever/whenever which is just a bad pattern for maintaining software in the long run.

Thank you for your understanding with all of this, I hope you aren't discouraged from opening issues. Bug reports and discussions do continue though I don't know where I stand on feature requests in general.

I'm much more into writing Neovim plugins using its Lua API as it provides an unmatched interface which is significantly faster than VimL and still brilliant to write plugins with.

**Comment by samarulmeu** [comment]
So there will be no _translate_ of the plugin to the new vim9?

Anyhow I wish you all the best in all your endeavors and thank you for all till now.

**Comment by SidOfc** [comment]
Ah I figured this question would indeed arise as Vim9 is a breaking change right?

**Short answer:**

I'm leaving it open, but it is unlikely if large portions break or need significant rewriting

**Long answer:**

It really does depend on how breaking it is, I don't think I can be bothered to rewrite mkdx in Vim9 if large portions break or need significant rewriting since if I were to rewrite mkdx at all, I would do so in Lua for Neovim only (sorry vanilla Vimmers, I too wish there was "one true" api which worked in both). I've kept mkdx backwards compatible since I'd feel quite sad myself if a plugin author decided to just drop support for not using the "exact" same editor while both have a _similar_ API.

I am fairly certain that someone will pick up the reins for markdown formatting with a new Vim9 markdown plugin. For me however, it means that just like original VimL, I'd have to learn some additional "obscure" bespoke language which I can never use anywhere else. I'd learn it "just" to port and maintain mkdx.

No disrespect intended to Bram or Vim here, I love the fact that both Vim and Neovim can co-exist and rival each other (in a non-toxic way preferably) for popularity because this drives them both forward. Perhaps I'm proven completely wrong and Vim9 will be the future, that is still to be determined but until then I'm sticking with Neovim and their bet on Lua :)

**Comment by samarulmeu** [comment]
In a way I was expecting your answer and it is understandable.

Maybe I should try neovim also. Let's see...

**Comment by SidOfc** [comment]
There is a chance that mkdx will keep working in regular Vim I think since it seems all Vim9 features are opt-in (from reading [vim9.txt](https://vimhelp.org/vim9.txt.html)). Even if this wasn't the case, if Vim offered an opt-out of Vim9 I also wouldn't shy away from implementing that.

And yeah I'd say go for it if you want to try Neovim, both editors are great albeit I myself much prefer the latter to the former :)
