### ISSUE TITLE
filetype of other filetypes is set to markdown when opening (having) markdown file (open)

### ISSUE THREAD

**Issue by kraxli** [SidOfc/mkdx#179]
**OS type**:

- [X] Unix
- [ ] Windows
- [ ] Other ([SPECIFY])

**Vim**:

- [ ] vim
- [X] neovim
- [ ] Other ([SPECIFY])

**Vim version**:

nvim:  0.8

**Reproduce steps**:

Example:

1. Open a markdown file.

**Expected**:

`Filetype` of other files should not be changed just because having a `markdown` file open

**Actual**:

other files, e.g. lua files get also `filtype=markdown`

**Comment by SidOfc** [comment]
This is not an issue with mkdx, I tested with _just_ mkdx as an active plugin. Some other plugin, plugin manager, or some configuration in your init.vim / init.lua is likely causing this.

I'll close this since I'm 99.9% sure this can be attributed to user configuration error. That said, if you do still experience this issue _after_ having tested mkdx in _isolation_ (that is, no other plugins or configuration settings loaded) please comment on this issue and share a minimal init.vim or init.lua file for me to check out.
