### ISSUE TITLE
is this plugin conflict with "preservim/vim-markdown"?

### ISSUE THREAD

**Issue by jackywu** [SidOfc/mkdx#183]
**OS type**:

- [x] Unix
- [ ] Windows
- [ ] Other ([SPECIFY])

**Vim**:

- [ ] vim
- [ ] neovim
- [x] Other (MacVim)

**Vim version**:
```
VIM - Vi IMproved 9.0 (2022 Jun 28, 编译于 Feb  7 2023 12:17:42)
macOS 版本 - x86_64
包含补丁: 1-1276
编译者 GitHub Actions 
```

**Expected**:

I install mkdx plugin, and write markdown for several days，but recently I realize that the syntax HightLight is not very good，so ，I return to find another enhanced syntax highlight plugin for markdown，and I wanna ask ，is this plugin conflict with "preservim/vim-markdown"? if it is，what it is？thanks a lot。

**Actual**:

**Comment by SidOfc** [comment]
As far as I'm aware there have not been any mentions of plugin conflicts. mkdx syntax highlighting is disabled by default to allow other plugins better suited/specifically built for syntax highlighting to be used instead.

If syntax highlighting does not look very good another cause may be the theme you're using since most of mkdx syntax groups (`:h mkdx-highlighting`) are linked to builtin groups.

At any rate, I don't think there's any issue with the syntax highlighting of mkdx. The issues you are having are most likely related to your personal configuration. It could very well be that mkdx linked highlight groups do not work well with your theme, but you can customize them as you wish if you so desire.

I will close this since I believe I answered the question in addition to providing information about how to work around it. Thank you for the question 👍

**Comment by jackywu** [comment]
thank you， SidOfc
