### ISSUE TITLE
Disable list recognition for rst-style directives

### ISSUE THREAD

**Issue by hellocode808** [SidOfc/mkdx#186]
I'm using a markdown parser that allows me to use rst-style directives within markdown. Syntax example:
```
.. details:: Details 1
    This is the content of the details element.
```

mkdx disrupts my writing here - I think because it recognizes the ".." as list starting with "." 
Output:
```
.. details:: Details 1
.
```

How do I disable the list-detection for these elements?

**Comment by SidOfc** [comment]
Hello @hellocode808, I just added a commit which I think fixes this issue. The reason this happened was due to list parsing allowing numbered lists to start with `[0-9.]+` so any line starting with a period would also be identified as a list. I've changed this expression to `\d[0-9.]*` so these cases are properly ignored.

Does this work for you as well?

**Comment by hellocode808** [comment]
Wow, such a quick fix!

Yes it works perfectly now. Thank you!
