### ISSUE TITLE
Numbered list error

### ISSUE THREAD

**Issue by paxtemper** [SidOfc/mkdx#3]
This happen when i have numbered list, and when i manual change some item in list for making changes to insert submember items.

```
Error detected while processing function mkdx#EnterHandler[18]..<SNR>105_NextListToken:
line   10:
E684: list index out of range: 2
E116: Invalid arguments for function str2nr(parts[idx]) + 1
```

**Comment by SidOfc** [comment]
Hi there,

I'd love to check this out but I'll need some more information before I can look into it.
Could you add the snippet of text (the list on which the function breaks) and the cursor position to the issue?

Cheers!

**Comment by paxtemper** [comment]
I use arch linux. My vim version is: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 19 2017 20:40:12)

so i have this:
```
1. one
2. two
3. three
```
Then i realize to i need 2.1 and 2.2 list items ( i know it is unusual but is case which is possible). So come back on item two and change it to 2.1. My cursor is on second line in normal mode. 
```
1. one
2.1| two point one
3. three
```
Then i press <kbd>o</kbd> to create 2.2 item. That is point when error is reported but 2.2 item is created successfully.

```
Error detected while processing function mkdx#EnterHandler[18]..<SNR>126_NextListToken:
line   10:
E684: list index out of range: 1
E116: Invalid arguments for function str2nr(parts[idx]) + 1
```

**Comment by SidOfc** [comment]
Wow, the issue got closed because of the commit message I guess. I wanted to reply to add some additional information and to ask you to update the plugin and see if you still experience this behaviour :)

Regarding the actual problem; It has to do with malformed indentation.
mkdx expects a sublist item, e.g. `2.1` to be indented in a `2` item, like this:

    1. item 1
    2. item 2
        2.1. subitem 1
        2.2. subitem 2

Instead of being used at the top level.
The reason you got this error is because all *later* coming list items also have to be incremented.
This happens by splitting the number by dots an incrementing the number based on the length of the resulting split list. In your case, the index to increment would be 1 because there are 2 parts in the number where you press `o` (`2.1` => `[2, 1]`).

Since then, it sees that the item with number `3.` has the same level of indentation. But in this case, the length of the number when split is only 1, because there is no number after the dot, e.g. (`3.` => `[3]`) so when it tries to increment, it fails since there is no index 1 in this list.

I've added a check to see if the index is out of range, in which case the calculation will be skipped.
