### ISSUE TITLE
Autocomplete + ncm broken

### ISSUE THREAD

**Issue by iicurtis** [SidOfc/mkdx#86]
I'm not sure if this is something to be fixed here or over at ncm2. 

Problem: If ncm2 has a suggestion box open and the user presses return to get a new list item, the list bullet `-` is just appended to the end of the current line and no newline is created.

**OS type**:

- [x] Unix
- [ ] Windows
- [ ] Other ([SPECIFY])

**Vim**:

- [ ] vim
- [x] neovim
- [ ] Other ([SPECIFY])

**Vim version**:

```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.2/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
```

**Reproduce steps**:

Example:

1. Use Plug or other to install mkdx, ncm2, and ncm2-bufword
1. Open a markdown file.
2. Paste the following example into the file:
```
- Buffer
- List
```
3. Then, enter insert mode at end of "List" and press enter.

**Expected**:

A new line with `- ` is created.

**Actual**:

We get `- List- `.

**Comment by SidOfc** [comment]
Hello! Thanks for reporting the issue, I'll try to look at it later today as I'm on my way to work right now. Will update when I know more

:+1:

**Comment by SidOfc** [comment]
I did not quite get to it yesterday but started investigating today, I found a solution for when no item is selected and enter is pressed. This unfortunately also applies when an item is selected from the completion menu so the enter character would now _always_ be inserted.

Since the intention of selecting an item and pressing enter most likely means "select item" and not "select item and insert newline", I'll have to find a solution for that scenario too.

I've already checked out whether I can do something with `pumvisible()` and `v:completed_item` but this does not seem possible since `v:completed_item` gets its data after a `CompleteDone` event which only gets triggered _after_ the enter handler gets called. This can be better summed up in a screenshot:

![image](https://user-images.githubusercontent.com/3225058/67144367-feb6d080-f275-11e9-977a-66754defa95d.png)

An alternative would be to set a (global) flag after executing the enter handler and listening for `CompleteDone` events to "undo" the inserted enter. This would likely lead to undesired behavior in other cases / use-cases... I'm going to let this sink in for a bit for now.

**Comment by SidOfc** [comment]
This one is quite tricky to "get right" due to the way mkdx handles enter currently. It may take a bit to come up with a solution so in the meantime I'd like to suggest using <kbd>Ctrl</kbd>+<kbd>E</kbd> to close the popup before pressing <kbd>Enter</kbd>.

While suboptimal, so far I haven't been able to prevent all undesired behavior yet. Keeping this issue open until it's fixed (hoping to have something by the end of the week).

**Comment by SidOfc** [comment]
Well, it is indeed a pretty tricky issue to fix, not even due to the issue itself per-se but also the amount of feature creep and some of my most god-forsaken variable naming that ended up in the plugin making it harder and more risky to modify.

Handling enter in a text editor is no easy task without messing it up in _some_ way, eventually...

I do think there's a solution though, but that would be separating out different major features of mkdx and breaking them up into their own plugins. Having seen the mess I created during my first rodeo with vimscript I think I can do better on code quality and testing fronts for sure.

Such structure would allow me to better define the responsibility of each "smaller" part of what mkdx tries to manage as a "whole" right now and would allow for easier testing of individual components.

This is how I will go forward, taking some part of mkdx and turning it into its own plugin using TDD. Perhaps mkdx can then be replaced by a combination of smaller, simpler and easier to maintain plugins that provide the same or even more functionality where it makes sense (I can imagine dead link checking is useful in many formats aside from markdown).

Apologies for the late reply btw, but yeah, I had to think about this for a bit :)

**Comment by Blacksuan19** [comment]
any progress with this? 
I am facing the issue with coc and nvim

**Comment by SidOfc** [comment]
@Blacksuan19 unfortunately I have no real solution for this. Basically, the order in which things seem to happen:

- You type some text, it matches some completion so a menu pops up
- You decide that you want to accept this completion and press \<Enter> as usual
- mkdx does NOT trigger yet, but your completion engine already inserts an answer, there is no way for me to know this answer (chosen completion) up front or register it.
-  finally, mkdx#EnterHandler gets triggered without knowing what to do since there is no way to check for a completion, ncm doesn't seem to expose it, (n)vim also doesn't expose it, so I'm left to guess.

With this in mind, a solution could be to rewrite the enter handler to trigger sooner, but...

While I can try to rewrite the enter handler in such a way that it actually registers enter presses sooner, that still does not get me any guaranteed answer about the completion without creating my own custom logic to keep track of changes in text, not something I like to rely on, and may then also break other plugins who need this "early access" to enter themselves.

This also poses another problem of doing this transparently for all cases e.g. trigger the "recording" of changes while still allowing completion menu's and who knows what else to pop up, do their thing, and then for me to regain control again in order to find out what is even allowed to happen.

ncm does offer some kind of "lock" functionality which would effectively disable it, but there is no reliable way for me to trigger and release this lock, leaving you with a possibly defunct ncm plugin due to mkdx. I do not know if coc has something like this but the issue would be the same unless coc provides some flags for other plugin authors to be able to hook into.

Another thing is that this is really a plugin combination problem, so one could argue it could also be handled (at least partially) by aforementioned ncm or coc plugins, say if they added hooks to know when a completion menu was opened, completed/escaped, and closed, I would be able to hook into that to provide necessary info for the enter handler. 

Then _another_ thing is that for every plugin, I'd have to learn their API, figure out what works / changed in each version, update my plugin to handle that. The inverse is true if I provide hooks into mkdx to allow other authors to set this on their end using the API I'd create.

So yeah, if you have any ideas whatsoever, you're very welcome to share :)

**Comment by SidOfc** [comment]
Going to close this for now, if more folks suffer from this feel free to reopen for discussion.
