### ISSUE TITLE
[bug] `mkdx` turns off markdown header folding

### ISSUE THREAD

**Issue by nocibambi** [SidOfc/mkdx#89]
**OS type**:

- [X] Unix: Ubuntu 18.04.4
- [ ] Windows
- [ ] Other ([SPECIFY])

**Vim**:

- [ ] vim
- [X] neovim
- [ ] Other ([SPECIFY])

**Vim version**: v0.2.2

**Reproduce steps**:

0. Have `let g:markdown_folding = 1` in `.vimrc` (I also tried without this setting, but this was my default before).
1. Open a markdown file.
2. Paste the following example into the file:
```markdown
## Today
* Fix the single most important thing
* Check the week planner
* Plan your day
```
3. Then, having the cursor on the first line (`## Today`) attempt to do close fold with `zc` in normal mode.

**Expected**: The `## Today` becomes folded

**Actual**: It does not fold and I have the error: `E490: No fold found`.

Folding starts to work if I

- disable the `mkdx` plugin in `.vimrc`
- run `:so .vimrc`
- run `:PlugInstall`
- reopen the markdown file (sometimes only after restarting nvim too)

**Comment by SidOfc** [comment]
Thanks for the detailed bug report, I'll look into it as soon as I can!
Hoping to have something by Wednesday :)

Cheers :+1:

**Comment by SidOfc** [comment]
Hello! I've checked it out and it seems to come from Tim's [vim-markdown](https://github.com/tpope/vim-markdown) plugin. Unfortunately they both use the same vim functionality (`foldmethod` and `foldexpr`) to fold different parts of the document.

In this case it is not really possible to provide an easy workaround so now, whenever `g:markdown_folding` is enabled, mkdx will not override `foldmethod` and `foldexpr`, thus allowing vim-markdown to do its job.

The only way I see this becoming a non-issue is by also providing the same fold functions that vim-markdown provides aside from mkdx's functionality. At some point I might look into it but unless heavily requested I'd rather not put the effort in just yet :)

**Comment by nocibambi** [comment]
Hi, Many thanks for your quick and elaborate answers. I really appreciate it. However, it still does not work for me, it does the exact same thing as I described above.

I checked and your commit cloned successfully, the respective lines are the same.

I am relatively new to Vim, so I have little idea what another thing can cause it.

Here is my .vimrc for reference.

```viml
""" Plugins
" Plugins will be downloaded under the specified directory.

call plug#begin('~/.vim/plugged')
" Declare the list of plugins.

" Fuzzy finder
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" Distraction free writing
Plug 'junegunn/goyo.vim' 

" Notational velocity
Plug 'https://github.com/alok/notational-fzf-vim'

" ctrl-P file searher
Plug 'ctrlpvim/ctrlp.vim'

" Markdown mappings
"Plug 'SidOfc/mkdx'

" link navigation in markdown
" Plug 'chmp/mdnav'

" A nice theme
" This does not work, probably because of this being neovim.
" Plug 'junegunn/seoul256.vim'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()


""" Settings
" Set color scheme
syntax enable
set background=dark
colorscheme solarized

" Set system clipboard as default"
set clipboard=unnamedplus

" Set whole word word wrapping
set linebreak

" When splitting focus new window
set splitbelow
set splitright

" Turn off case sensitive search and use smartcase
set ignorecase
set smartcase

" Search path for Notational Velicity notes 
let g:nv_search_paths = ['~/Dropbox/Notes/Notes']

" Make ctrlp use ripgrep as a search tool
" Filtered for .md files
let g:ctrlp_user_command = 'rg %s --files --hidden --color=never --glob "*.md"'

""" Markdown folding
let g:markdown_folding = 1

let g:mkdx#settings     = {
	\ 'fold': { 'enable': 1 }
\}


""" Key remaps
" Remove the search highlights with escape
nnoremap <esc> :nohlsearch<return><esc>

" Instert empty line below/above without entering insert mode
nnoremap oo m`o<Esc>``
nnoremap OO m`O<Esc>``
set timeoutlen=200

" Instert curret date
nnoremap <F5> "=strftime("%F")<CR>P
inoremap <F5> "=strftime("%F")<CR>P

" Open specific files .vimrc
nnoremap <leader>v :e ~/.vimrc<CR>
nnoremap <leader>o :e ~/Dropbox/Notes/Notes/Organizer.md<CR>
" nnoremap <leader>j :e ~/Dropbox/Notes/Notes/Journal.md<CR>

" Ctrl-S to save
nnoremap <silent> <c-s> :w<CR>
```

**Comment by SidOfc** [comment]
Hmmn alright, interesting!

I'll have a look tomorrow evening (got plans tonight :P), we use the same plugin manager so for that reason I'll run vim with your config and plugins, see if I can reproduce.

Thanks for testing and sharing your .vimrc, it really helps and I'll get back to you asap! :+1:

**Comment by SidOfc** [comment]
@nocibambi this is unrelated to the issue you're having, but I thought it would be good to know that you are using `colorscheme solarized` yet do not have any plugins installed which supply it.

The reason that might still work for you is because you probably installed it before using vim-plug, and thus can still be found in your `~/.vim/plugged` directory. Then later when doing cleanup, you may have accidentally removed one too many plugins :)

Just pointing it out so that you can fix it for your future self :)

For now, my friend called me up for some gaming so I'm off for tonight but will check back in tomorrow and do some proper work!

**Comment by nocibambi** [comment]
Hey @SidOfc!

First of all, many thanks for your consistent interest in this case. 

Also many thanks for picking out such things from my `.vimrc`. Actually, I do **not** have the package under my `plugged` directory (nor I have a `.color` directory).  I remember that it was not a clean install, but now I forgot what was the issue. Another thing to sort out. :)

Anyways, this is far from being an urgent matter, even though I would love to use your plugin with header folding. So, have a great gaming session (although you probably already had it)!

**Comment by SidOfc** [comment]
Hi @nocibambi!

Interesting that your color scheme worked, I wonder how haha!

Also, I just pushed a few more commits, it took a while before I figured it out. I actually disabled all calls that did something with either `foldexpr` or `foldmethod` but they kept resetting!

Working up to the point of reaching insanity, there's always one key move I try, which is to selectively comment out blocks in the "init" file which wires the entire show together. I do this to the point that no code remains.

When it still didn't work with only this line left uncommented:
```viml
if exists('b:did_ftplugin') | finish | else | let b:did_ftplugin = 1 | endif
```

I knew there was some possibility of a conflict with other plugins since it is mentioned in the [Vim Tips Wiki - File type plugins](https://vim.fandom.com/wiki/File_type_plugins) section and when I checked the source for the built-in markdown plugin I [found it](https://github.com/tpope/vim-markdown/blob/f35c43c535af40dc045d55dd459969b6f31d4128/ftplugin/markdown.vim#L6-L8) :)

I renamed my `b:did_ftplugin` to `b:did_ftplugin_mkdx` which solved the problem.
I tested it with your exact vimrc and plugins installed, even leaving `g:mkdx#settings.fold.enable = 1` to test my `g:markdown_folding` guard.

Let me know if it works for you, or wether the plot will thicken even more :crossed_fingers: :crossed_fingers:

**Comment by nocibambi** [comment]
Hi @SidOfc,

You really did it! I just checked and it works like a charm. 

Many great thanks, you just made this world a better place! :smiley:

**Comment by SidOfc** [comment]
Good stuff! Enjoy the plugin, if you actually encounter the issue again feel free to reopen! And again, cheers for the report and sharing your vimrc -- that **really** moved mountains in this case :+1: 

Last but not least, have a good one :wave:
