### ISSUE TITLE
Quote marks 

### ISSUE THREAD

**Issue by samarulmeu** [SidOfc/mkdx#90]
Thanks for this great plugin that, for me, replaced all the markdown related plugins. I still have to get familiarized with all that it can offer. But I found something rather annoying when using quoted text. Instead of getting a single `>` when starting a new line, I get two of them. 

**OS type**:

- [x] Unix

**Vim**:

- [x] vim

**Vim version**:

VIM 8.1

**Reproduce steps**:

Example:

1. Open a markdown file.
2. Paste the following example into the file:

```
> The quick brown fox jumps...
```

3. Then, press `enter` in INSERT mode.

**Expected**:

```
> The quick brown fox jumps...
>
```

**Actual**:

```
> The quick brown fox jumps...
> >
```

**Comment by SidOfc** [comment]
Hi @samarulmeu!

I've confirmed the behavior and will look into it as soon as I can, though it might take a few days due to pre-planned events, apologies for the inconvenience 😅 

Thank you for reporting this issue! 👍

**Comment by samarulmeu** [comment]
No problem. Take your time!

**Comment by SidOfc** [comment]
@samarulmeu couldn't help but take a look, short version:

1. I disabled all code I knew was responsible for inserting the quote marks
2. quote mark still inserted -> maybe some vim setting changed / markdown support "improved"?
3. (1 minute later) entirely disabled mkdx, behavior didn't exist, back to square 1
4. print all variables in the eventual "line" that gets injected into the buffer when pressing enter
5. two out of three things returned a quote mark, one of my brilliantly named variables `t` was matching the same quote mark managed by other code which caused the duplication.

Solution was to [prevent `t` from ever becoming a quote mark](https://github.com/SidOfc/mkdx/commit/5a077c8663857d014d7da0ddef80cc95321bedba) since it should not hold that meaning as some other variable takes care of it. I also added some tests to check for this in future releases, all other "listy" things were tested except of course, the quotes :man_facepalming: :joy:  

You can pull master and things should work as intended once again with regards to quotes, let me know if the issue persists. Otherwise feel free to close, thanks for reporting :+1:

**Comment by samarulmeu** [comment]
Wow, so quickly! Thank you so much! It's perfect now.

I have two small issues, though. So I'll continue here, but I'm closing this issue as it was solved. I don't think is necessary to start another one.

So, the **first** one:

Do you have any idea of how to insert blank lines inside a quote field. If I press `Enter` on an empty line it will delete the quotation mark (nice feature, must be there), but even if I add one or two more spaces and press `Enter` the quotation mark is still deleted. I even tried `Shit+Enter`. I was thinking about this because, sometimes, I am quoting more than one paragraph...

And the **second** one:

I'm using *Vundle* as a plugin manager and every time I do an update I get this error:

```
Error running :helptags /home/.../.vim/bundle/mkdx/doc
```

It's the only plugin with this kind of error. 

Anyway, thanks again and keep up the great work you're doing with **mkdx**.

**Comment by SidOfc** [comment]
Hey @samarulmeu!

Cheers, I do my best to keep up with fixing issues as they come up :)

As for the quotes, mkdx has no functionality to support this. The way it currently works is like in word when adding new bullet / number list items, pressing enter twice simply takes you "out of the list".

That said though, a solution could be to add a feature which uses ctrl+enter, since shift enter is used for multi-line indented list item insertion :) that being said I'm not sure if supporting ctrl+enter is easy (shift+enter already is quirky to set up 😅).

I'm also not sure if it would be needed though, because mkdx also has a mapping for visual mode which allows you to [quote a selection using `<prefix>'`](https://github.com/SidOfc/mkdx/blob/master/README.md#toggling-quotes). If this is not something that fits your workflow though I'm open for suggestions in a new issue :)

I'll also take a look at the Vundle error in time, not sure if it is something specific to Vundle or other plugin managers being more "fault tolerant" towards doc files, cheers for letting me know!

**Comment by samarulmeu** [comment]
Thank you for your answer and time! 

I was thinking that this could rise some issues with the mapping and I think that it is ok for the time being. 

One way, I don't know how easy is to implement, could something I mentioned in my previous answer: check if `>` is followed by an empty space ` ` and if so then if `Enter` is pressed then leave the `>` mark and start a new line (also with `>` as first character), if `Enter` is pressed immediately after the `>`, have the quote mark deleted and go to a new line.

Hope my English was good enough in explaining. 

Have a great day!

**Comment by SidOfc** [comment]
You explained it well, thanks for putting in the time to write it up!

Actually, mkdx already inserts that space so you can continue to type your quote without needing to type it first. If I don't insert the space after the ">", it feels janky when you _do_ want to continue the same paragraph of a quote on a new line. Because then you'd have to type space + "your text" on every new line.

Since I think there are a lot of cases in which a quote is "one paragraph / one line" rather than "multiple paragraphs", I am a little bit reluctant to support this for everyone.

That being said, it could be another setting for mkdx which is disabled by default (so you have to opt-in, rather than opt-out). Once enabled, you could then get the behavior you want, though it will break your flow for adding quotes that don't contain more than a single paragraph of text.

I'm willing to implement it based on the above details. If you'd like to see this feature implemented you are welcome to [open a new issue](https://github.com/SidOfc/mkdx/issues/new) :)
