### ISSUE TITLE
[Feature request] Empty line quote option

### ISSUE THREAD

**Issue by samarulmeu** [SidOfc/mkdx#91]
As we've discussed in Issue #90 would it be possible to have an empty new line in a quote environment? 

The plugin now, if you press enter in a quote paragraph, automatically inserts the `>` quote mark followed by a space. But if you press Enter, the quote mark disappears (a nice feature that should remain). The option I'm thinking about is that if you press space after the `> ` and then enter (so you will have two spaces) you still are in the quoted environment. 

Something like this

```
> Something
>  
> 
```

Thank you for your time!

**Comment by SidOfc** [comment]
Heya @samarulmeu!

I read your idea and thought it was "quote" (quite) good :smile:.  It does not break existing behavior or require any extra mappings. I've [added a small note](https://github.com/SidOfc/mkdx#toggling-quotes) in the README to clarify how one can create a multi-block quote. Thank you for your contribution!

Let me know if there are any issues, otherwise you may close this :+1:

**Comment by samarulmeu** [comment]
Thank you so much! That's what I call great support. 

As I've started using exclusively this plugin I hope it will not be too much trouble if I will bother you with another request. As this option could already be present, I'm reluctant in starting a new issue, but it will be possible to have some lines selected and then have a mapping for wrapping them within a block code ```, the way `\<PREFIX\>\`` works?

**Comment by SidOfc** [comment]
@samarulmeu hmmn I think `` <PREFIX>` `` still isn't used at the moment, it seems like a mapping mkdx should have though, since there's a lot of wrapping for other parts of markdown formatting already.

That said I need to look into wrapping block selections in visual mode to see what I can achieve there, feel free to open an issue for this one as I don't think it's there yet. If I do find it somewhere I'll close the issue no worries :)

Thanks for the feedback and bug reports so far 👍
