### ISSUE TITLE
[Bug]: Toggle quote

### ISSUE THREAD

**Issue by samarulmeu** [SidOfc/mkdx#94]
Hello,

When selecting more than on paragraph of text and using the toggle quote mapping, I do not get the expected behavior as the  empty lines are not inside the quote field.

**OS type**:

- [x] Unix

**Vim**:

- [x] vim

**Vim version**:

Vim 8.1

**Reproduce steps**:

Example:

```
Some text. 

Some other text
```

**Expected**:

```
> Some text. 
>
> Some other text
```

**Actual**:

```
> Some text. 

> Some other text
```

Thank you for your time and help!

**Comment by SidOfc** [comment]
Hi @samarulmeu! I relabeled this one a feature request because it wasn't actually a bug, but rather an unimplemented feature, the code deliberately skipped empty lines when toggling quotes :)

I've now implemented a different function which takes care of multi-paragraph selections,  leading and trailing empty lines will remain unaffected.

It's in master, feel free to pull, I'm not sure if I'm going to get to the other feature request tonight but will try :)

As usual, you may close if it is fixed, thank you for the good suggestion! :+1:

**Comment by samarulmeu** [comment]
Again, perfect job. Thank you!
