### ISSUE TITLE
[Bug] Bold and italic rendering

### ISSUE THREAD

**Issue by samarulmeu** [SidOfc/mkdx#97]
I think the plugin fails to render the bold and italic highlighting. Please keep the different coloring of italic, bold and italic&bold. 

**OS type**:

- [x] Unix

**Vim**:

- [x] vim

**Vim version**:

VIM 8.1

**Reproduce steps**:

Example:

1. Open a markdown file.
2. Paste the following example into the file:

`***something*** or *_something_*`

**Expected**:

***something***

**Actual**:

something.

**Comment by SidOfc** [comment]
Will look into fixing this when I can :+1:

**Comment by SidOfc** [comment]
@samarulmeu actually, I did some more research, it is the default markdown highlighter which does not apply bolds and italics, or is dependent on your terminal settings perhaps.

mkdx has specific styling for text that is bold *and* italic, but abstains from controlling / trying to control everything (further explained in #96).

The syntax styles that need to be fixed would be:
- `markdownBold`
- `markdownItalic`

These syntax groups can be modified by you in your vimrc file, though I've never done it because I personally don't like the "chaos" it brings to the text I see, so I put no effort into making it work for me. I do have "some" modified parts though, so posting a screenshot as an example of how syntax highlight rules could look (these are not the rules you want to modify!):

![image](https://user-images.githubusercontent.com/3225058/76862084-d7ccec80-685d-11ea-8195-bcb883934160.png)


If you find a solution and think it could be easily implemented in mkdx, you are free to send a PR with an updated `after/syntax/markdown/mkdx.vim` file :)

**Comment by SidOfc** [comment]
Also, my word on this is not final because I closed it, do not feel like I'm shutting you down, if you feel this issue needs to be reopened because it is valid then please do. Happy to keep discussing if we disagree :)

**Comment by samarulmeu** [comment]
So, here is the rendering i get 

![boldItalic](https://user-images.githubusercontent.com/39216570/76875983-f3de8700-6879-11ea-9c95-b75ec976e99a.png)

I just thought it will be nice that the last rendering will be closer to *reality*. Although I'm fine with plain markdown also, but from time to time I find it easier to have a WYSIWYG perspective.

I'm fine with closing the  issue and I will also try to find a solution.

**Comment by SidOfc** [comment]
Ah I'm a retard lol!

Completely misread that... This is definitely something I can take a look at and should be expected to work!

Apologies for the premature close :+1:

**Comment by SidOfc** [comment]
@samarulmeu added bold style to `mkdxBoldItalic` syntax highlighting group. It doesn't show up for me (Have to change more configs for that), does it show up for you?

**Comment by samarulmeu** [comment]
I think we are getting there. 

May I suggest that we change the line 56 from ` after/syntax/markdown/mkdx.vim` into:

```
highlight default      mkdxBoldItalic   ctermfg=215 guifg=#ffaf5f cterm=bold,italic term=bold,italic gui=bold,italic
```

I thought that the color will be closer to the original one and we get this way both italic and bold. But it is just a suggestion. 

Thank you again!

Now, that I'm getting into this maybe I should start working on the issue #96

**Comment by SidOfc** [comment]
Hi @samarulmeu!
 Very good suggestion to make the style bold as well as italic :sweat_smile:  I'm going to check out colors a bit better next time I work on mkdx, I used the ones from my own color scheme rather than Vim's defaults during testing hehe...

May I ask where you got those `ctermfg` and `guifg` colors from? A different syntax style or?
Because before this change `mkdxBoldItalic` linked to `Delimiter` highlighting group, and `Delimiter` by default is linked to `Special` which has `ctermfg=224` and `guifg=Orange`.

My theme actually overrides this with the color codes you're seeing right now (but they look different because our schemes are different). I'm going to look into making the highlighting respect colorscheme changes to existing highlight groups (using `link` won't work if only parts of it need change).

Will report back when I know more, in the meantime at least the style should be `bold,italic` in master now :+1:.

**Comment by samarulmeu** [comment]
Hi @SidOfc !

Actually the color codes I got from [here](https://vim.fandom.com/wiki/Xterm256_color_names_for_console_Vim). I looked there for a color similar to the one in the screenshot I provided above in one of my comments. I thought that it will look nicer with a brownish font, forgetting about the theme. Your choice `ctermfg=14 guifg=#8a553f`is rendered as a neon light blue which is not so nice on the eye and in my vim it looks like this:

![neon](https://user-images.githubusercontent.com/39216570/76950022-1c19c480-6912-11ea-8669-449fcb7ba17f.png)

So you make the choice for the color.

**Comment by samarulmeu** [comment]
Or maybe just don't specify a color and let the theme choose it?

**Comment by SidOfc** [comment]
@samarulmeu this will not work since it is a custom highlighting group. It has no "pre existing" rules so to speak (maybe you'll see bold and italic styles mixed in bold-italic texts instead). For this reason I need to "inherit" from `Delimiter` which is what `mkdxBoldDelimiter` _is also_ linked to.

Problem is I need to customize `Delimiter` to add the bold and italic styles and if I need to do that, I can't use `highlight link` from my current understanding. So the next step for me is just to figure out how to "restyle" based on theme.

The idea I have is to "read styling" (need to check if possible, likely is though) from the `Delimiter` group and then run an `exe` command to create the `mkdxBoldItalic` group dynamically.

**Comment by samarulmeu** [comment]
Already seems complicated. Maybe just choose a color. From my part I think that the problem is solved, so I will close this for now. 

As a workaround I will define the color for `mkdxBoldItalic` in my `vimrc` until you find a solution.

**Comment by SidOfc** [comment]
@samarulmeu I pushed another update which should fix the color inconsistency, is it better?
